name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.3
      with:
        vs-version: '[17.0,18.0)'

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3
      with:
        msbuild-architecture: x64

    - name: Install workloads
      run: |
        dotnet workload install windows
        dotnet workload install maui
        dotnet workload install wasm-tools

    - name: Restore NuGet packages
      run: nuget restore AIPal.sln

    - name: Build with MSBuild
      run: msbuild AIPal.sln /p:Configuration=Release /p:Platform=x64

    # Uncomment when build is working
    # - name: Test
    #   run: dotnet test --verbosity normal --configuration Release
